### PR TITLE
Add support for pushgateway

### PR DESCRIPTION
**Pull request by yolossn**
Adds support for pushgateway, oauth2 is not setup for pushgateway as it will make accessing it from code difficult. 
pushgateway support inbuilt basic auth and it can be configured from the yaml. 

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

### CODE REVIEW

**Review by iaguis — COMMENTED** [review]
I haven't tested it but this looks reasonable, nothing stands out as wrong to me.

Have you tested manually on the server?

Also, we're missing configuration for Caddy, right?

**Comment by yolossn** [comment]
Hey, I don't have access to the dev server to test it. I have added the `/pushgateway/*` route to Caddyfile.

**Comment by iaguis** [comment]
> Hey, I don't have access to the dev server to test it. I have added the `/pushgateway/*` route to Caddyfile.

Somehow I missed this, sorry! I've added you to the server, you should be able to log in with `ssh root@monitoring.flatcar-linux.net`.

**Review by iaguis — APPROVED** [review]
LGTM. Feel free to merge if you've tested it.

**Pull request merged**
